[database]
host="localhost"
port=6879
user="user"
password="password"
database="proton"
sslmode="disable"

[server]
port=8080

[keys]
jwt_signing_key="jwt_signing_key"

[pubber]
user_agent="Proton User Agent"
max_delivery_depth=5
max_inbox_forwarding_depth=5
