version: '3'
services:
  proton:
    build: .
    ports:
      - '8080:8080'
    environment:
      - PT_SERVER_PORT=8080
      - PT_DATABASE_HOST=db
      - PT_DATABASE_PORT=5432
      - PT_DATABASE_USER=proton
      - PT_DATABASE_PASSWORD=proton
      - PT_DATABASE_DATABASE=proton
      - PT_DATABASE_SSLMODE=disable
      - PT_PUBBER_USER_AGENT=Proton
      - PT_PUBBER_MAX_DELIVERY_DEPTH=5
      - PT_PUBBER_MAX_INBOX_FORWARDING_DEPTH=5
    depends_on:
      - db
  db:
    image: library/postgres
    environment:
      - POSTGRES_USER=proton
      - POSTGRES_PASSWORD=proton
      - POSTGRES_DB=proton
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data